# Config for https://github.com/toolmantim/release-drafter
name-template: 'Play $NEXT_MINOR_VERSION'
tag-template: '$NEXT_MINOR_VERSION'
filter-by-commitish: true
commitish: master

change-template: '- $TITLE [#$NUMBER] by [@$AUTHOR](https://github.com/$AUTHOR)'
template: |
  # :mega: Play $NEXT_MINOR_VERSION Released
  
  The Play Team is proud to announce the release of Play $NEXT_MINOR_VERSION. This release adds many new features and continues our efforts to make Play more modular, flexible, and secure. Play $NEXT_MINOR_VERSION is the result of more than **X months** of relentless work from our fantastic community, comprehending **more than a thousand (TODO?) changes** made from **X contributors**.
 
  $CONTRIBUTORS
  
  ## Full Changelog
  
  Following pull requests got merged for this release:
  
  $CHANGES
  
  For more details see the [full list of changes](https://github.com/playframework/playframework/compare/$PREVIOUS_TAG...$NEXT_MINOR_VERSION/) and the [$NEXT_MINOR_VERSION milestone](https://github.com/playframework/playframework/issues?page=1&q=milestone%3A%22$NEXT_MINOR_VERSION%22).
