name: Publish

on:
  push:
    branches: # Snapshots
      - master
    tags: # Releases
      - '**'

jobs:
  publish-artifacts:
    name: Publish / Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: releasing
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event.ref_type }}
          echo ${{ github.ref }}
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}

