name: Publish

on:
  push:
    branches: # Snapshots
      - master
    tags: ["*"] # Releases
  create:
    tags:
      - "**"

jobs:
  publish-artifacts:
    name: Publish / Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: releasing
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event.ref_type }}
          echo ${{ github.ref }}
