name: Trigger cache invalidation

on:
  workflow_dispatch:
    inputs:
      bytes:
        required: true
        default: 10737170860

jobs:
  trigger-cache-invalidation:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/cache@v3
        with:
          path: /tmp/big_file
          key: ${{ github.run_id }}-${{ github.run_attempt }}
      - run: |
          head -c ${{ github.event.inputs.bytes }} < /dev/urandom >> /tmp/big_file
          ls -l /tmp/big_file
