name: Invalidate Cache

on:
  workflow_dispatch:
    inputs:
      counter:
        required: true
      amount:
        required: true

jobs:
  flush:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/cache@v3
        with:
          path: /tmp/flush
          key: mykey # ${{ github.run_id }}-${{ github.run_attempt }}
      - run: |
          for i in {1..${{ github.event.inputs.counter }}}; do head -c ${{ github.event.inputs.amount }} < /dev/urandom >> /tmp/flush; done
          ls -l /tmp/flush
          du /tmp/flush
