name: Check

on:
  pull_request: # Check Pull Requests

  push:
    branches:
      - master # Check master branch after merge

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs-tests:
    name: Just a test job
    uses: mkurz/release-drafter-test/.github/workflows/sbt-matrix.yml@master
    with:
      matrix: >-
        {
          '{0}JAVA': [ "11", "8" ],
          '{0}SCALA': [ "2.12.15", "2.13.8" ],
          '{0}SBT': [ "1.3.13", "1.6.2" ],
          'exclude' : [
            { "{0}JAVA": ${{ github.event_name != 'schedule' || '11' }}, "{0}SCALA": "2.12.15", "{0}SBT": "1.3.13" }
          ],
        }
      cmd: |
        echo $MATRIX_SCALA
        echo $CACHE_HIT_COURSIER
        echo ${{ github.event_name == 'schedule' || github.run_id }}
