name: Check

on:
  pull_request: # Check Pull Requests

  push:
    branches:
      - master # Check master branch after merge

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
#  my_playground_job_1:
#    runs-on: ubuntu-20.04
#    steps:
#      - run: |
#          jq -n -r '$in | to_entries|map("MATRIX_\(.key|ascii_upcase)=\(.value|tostring)")|.[]' --argjson in '{ "java": "11", "scala": "2.13.8", "sbt_test_task": "test", "folder": "." }' >> $GITHUB_ENV
#      - run: |
#          echo "Hello world!"
  docs-tests:
    name: Just a test job
    uses: mkurz/release-drafter-test/.github/workflows/sbt-matrix.yml@master
    with:
      java: >-
         [ "11", "8" ]
      add-dimensions: >-
        { "scala": [ "2.12.15", "2.13.8" ], "steps": [ "*1of3", "*2of3", "*3of3" ], "sbt_version": [ "1.3.13", "1.6.2" ] }
      exclude: >-
        [ { "sbt_version": "1.3.13", "java": "11" } ]
      cache-key: "test-{0}-substition"
      cache-path: "$HOME/.ivy/local/"
#      env: SBT_VERSION=1.6.2
#      matrix: >-
#        {
#          '{0}JAVA': [ "11", "8" ],
#          '{0}SCALA': [ "2.12.15", "2.13.8" ],
#          '{0}SBT': [ "1.3.13", "1.6.2" ],
#          'exclude' : [
#            { "{0}JAVA": ${{ github.event_name == 'schedule' || '11' }}, "{0}SCALA": "2.12.15", "{0}SBT": "1.3.13" }
#          ],
#        }
      cmd: |
        echo $MATRIX_JAVA
        echo $MATRIX_SCALA
        echo $CACHE_HIT_COURSIER
        echo ${{ github.event_name == 'schedule' || github.run_id }}
