name: Check

on:
  pull_request: # Check Pull Requests

  push:
    branches:
      - master # Check master branch after merge

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:

