name: SBT command on matrix Java/Scala versions

on:
  workflow_call:
    inputs:
      matrix:
        type: string
        required: true
      cmd:
        type: string
        required: true
      env:
        type: string
        required: false
        default: ""
      cache-key:
        type: string
        required: false
        default: ""
      cache-path:
        type: string
        required: false
        default: ""

jobs:
  cmd:
    name: ${{ toJSON(matrix) }}
    runs-on: ubuntu-20.04
    strategy:
      # WA: https://github.community/t/reusable-workflow-with-strategy-matrix/205676/6
      matrix: ${{ fromJson(inputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Set ENV variables
        if: inputs.env != ''
        run: echo '${{ inputs.env }}' >> $GITHUB_ENV

      - name: Coursier Cache
        id: coursier-cache
        uses: coursier/cache-action@v6.3

      - name: Custom Cache
        uses: actions/cache@v2
        if: ${{ inputs.cache-key != '' && inputs.cache-path != '' }}
        with:
          key: ${{ inputs.cache-key }}
          path: ${{ inputs.cache-path }}

      - name: Install Adoptium Temurin OpenJDK
        uses: coursier/setup-action@v1.2.0-M3
        with:
          jvm: adoptium:${{ matrix.java }}

      - name: Print helpful configs and files and show environment
        run: |
          echo "$ cat /etc/sbt/jvmopts"
          cat /etc/sbt/jvmopts || true
          echo ""
          echo "$ cat /etc/sbt/sbtopts"
          cat /etc/sbt/sbtopts || true
          echo ""
          echo "$ env"
          env
          echo "ls -alFhR ~/.ivy2 | grep play | grep jar"
          ls -alFhR ~/.ivy2 | grep play | grep jar || true
          echo "ls -alFhR ~/.cache/coursier | grep play | grep jar"
          ls -alFhR ~/.cache/coursier | grep play | grep jar || true

      - name: Run sbt command
        run: ${{ inputs.cmd }}
#       "{0}JAVA": "11"
        env: ${{ fromJSON(format('Hello \"{0}\" {1} {2}', 'Mona', 'the', 'Octocat')) }}
#        env: ${{ fromJSON(format('${0}: 11', 'MATRIX_')) }}
#        env: ${{ fromJSON(format(toJSON(matrix), 'MATRIX_')) }}

      - name: Cleanup before cache
        shell: bash
        run: |
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
